const FlagList = {
    CAD: {label: 'Canadian Dollar', flag: require('../images/flags/canada.png')},
    AUD: {label: 'Australian Dollar', flag: require('../images/flags/australia.png')},
    BGN: {label: 'Bulgarian Lev', flag: require('../images/flags/bulgaria.png')},
    BRL: {label: 'Brazilian Real', flag: require('../images/flags/brazil.png')},
    CHF: {label: 'Swiss Franc', flag: require('../images/flags/switzerland.png')},
    CNY: {label: 'Chinese Renminbi', flag: require('../images/flags/china.png')},
    CZK: {label: 'Czech Koruna', flag: require('../images/flags/czech.png')},
    DKK: {label: 'Danish Krone', flag: require('../images/flags/denmark.png')},
    GBP: {label: 'United Kingdom Pound', flag: require('../images/flags/kingdomUnited.png')},
    HKD: {label: 'Hong Kong Dollar', flag: require('../images/flags/HongKong.png')},
    HRK: {label: 'Croatian Kuna', flag: require('../images/flags/croatia.png')},
    HUF: {label: 'Hungarian Forint', flag: require('../images/flags/hungary.png')},
    IDR: {label: 'Indonesian rupiah', flag: require('../images/flags/indonesia.png')},
    ILS: {label: 'Israeli Shekel', flag: require('../images/flags/israel.png')},
    INR: {label: 'Indian Rupee', flag: require('../images/flags/india.png')},
    JPY: {label: 'Japanese Yen', flag: require('../images/flags/japan.png')},
    KRW: {label: 'South Korean won', flag: require('../images/flags/koreaSouth.png')},
    MXN: {label: 'Mexican peso', flag: require('../images/flags/mexico.png')},
    MYR: {label: 'Malaysian ringgit', flag: require('../images/flags/malaysia.png')},
    NOK: {label: 'Norwegian krone', flag: require('../images/flags/norway.png')},
    NZD: {label: 'New Zealand dollar', flag: require('../images/flags/newZealand.png')},
    PHP: {label: 'Philippine Peso', flag: require('../images/flags/philippines.png')},
    PLN: {label: 'Polish Zloty', flag: require('../images/flags/poland.png')},
    RON: {label: 'Romanian Leu', flag: require('../images/flags/romania.png')},
    RUB: {label: 'Russian Ruble', flag: require('../images/flags/russia.png')},
    SEK: {label: 'Swedish Krona', flag: require('../images/flags/sweden.png')},
    SGD: {label: 'Singapore Dollar', flag: require('../images/flags/singapore.png')},
    THB: {label: 'Thai Baht', flag: require('../images/flags/thailand.png')},
    TRY: {label: 'Turkish Lira', flag: require('../images/flags/turkey.png')},
    USD: {label: 'US Dollar', flag: require('../images/flags/america.png')},
    ZAR: {label: 'South African rand', flag: require('../images/flags/africaSouth.png')},
    EUR: {label: 'European euro', flag: require('../images/flags/euro.png')},
};

export default FlagList;